"""Board texture classification + GTO-approximate strategy tables (9 buckets).

Strategy tables can be loaded from pre-computed JSON (data/strategies.json)
generated by `python -m solve.generate`. Falls back to hand-tuned defaults
if the JSON file doesn't exist.
"""

import json
import os
from collections import Counter
from treys import Card

# Board textures
MONOTONE = 'monotone'
PAIRED = 'paired'
WET = 'wet'
HIGH_DRY = 'high_dry'
LOW_DRY = 'low_dry'

TEXTURES = [MONOTONE, PAIRED, WET, HIGH_DRY, LOW_DRY]

TEXTURE_LABELS = {
    MONOTONE: 'Monotone (3+ same suit)',
    PAIRED: 'Paired board',
    WET: 'Wet (connected + two-tone)',
    HIGH_DRY: 'High & dry (broadway, rainbow)',
    LOW_DRY: 'Low & dry (rainbow, unconnected)',
}

ACTION_LABELS = {
    'check': 'Check',
    'bet_s': 'Bet 33%',
    'bet_m': 'Bet 66%',
    'bet_l': 'Bet 100%',
    'fold': 'Fold',
    'call': 'Call',
    'raise': 'Raise',
}


def classify_texture(board):
    """Classify board into one of 5 texture categories."""
    ranks = [Card.get_rank_int(c) for c in board]
    suits = [Card.get_suit_int(c) for c in board]

    suit_counts = Counter(suits)
    rank_counts = Counter(ranks)

    if max(suit_counts.values()) >= 3:
        return MONOTONE

    if max(rank_counts.values()) >= 2:
        return PAIRED

    sorted_ranks = sorted(ranks)
    is_two_tone = max(suit_counts.values()) >= 2
    max_gap = max(sorted_ranks[i + 1] - sorted_ranks[i] for i in range(len(sorted_ranks) - 1))
    is_connected = max_gap <= 2

    if is_two_tone and is_connected:
        return WET

    high_count = sum(1 for r in ranks if r >= 8)  # T+
    if high_count >= 2:
        return HIGH_DRY
    return LOW_DRY


# ================================================================
# Strategy tables: 9 buckets × 5 textures
# {(position, texture, bucket): {action: probability}}
#
# Bucket key:
#   premium  = Full house+, nut flush, top set on dry
#   nut      = Set, non-nut flush, top two pair, combo draw
#   strong   = Overpair QQ+, TPTK, straight, low flush
#   good     = Overpair TT-JJ, TP good kicker, trips on wet
#   medium   = Low overpair, TP weak kicker, middle pair
#   draw     = Flush draw, OESD
#   weak_made = Bottom pair, underpair
#   weak_draw = Gutshot, backdoor draw
#   air      = Nothing
# ================================================================

# --- OOP acting first ---
OOP_STRATEGY = {
    # PREMIUM — build the pot, slowplay some on dry to trap
    ('OOP', 'high_dry', 'premium'):  {'check': 0.40, 'bet_m': 0.20, 'bet_l': 0.40},
    ('OOP', 'low_dry', 'premium'):   {'check': 0.35, 'bet_m': 0.25, 'bet_l': 0.40},
    ('OOP', 'wet', 'premium'):       {'check': 0.10, 'bet_m': 0.25, 'bet_l': 0.65},
    ('OOP', 'monotone', 'premium'):  {'check': 0.15, 'bet_m': 0.20, 'bet_l': 0.65},
    ('OOP', 'paired', 'premium'):    {'check': 0.35, 'bet_m': 0.25, 'bet_l': 0.40},

    # NUT — fast-play on wet, mix on dry
    ('OOP', 'high_dry', 'nut'):   {'check': 0.25, 'bet_m': 0.30, 'bet_l': 0.45},
    ('OOP', 'low_dry', 'nut'):    {'check': 0.20, 'bet_m': 0.35, 'bet_l': 0.45},
    ('OOP', 'wet', 'nut'):        {'check': 0.10, 'bet_m': 0.30, 'bet_l': 0.60},
    ('OOP', 'monotone', 'nut'):   {'check': 0.15, 'bet_m': 0.30, 'bet_l': 0.55},
    ('OOP', 'paired', 'nut'):     {'check': 0.20, 'bet_m': 0.35, 'bet_l': 0.45},

    # STRONG — solid value bets, mostly medium sizing
    ('OOP', 'high_dry', 'strong'):  {'check': 0.20, 'bet_m': 0.55, 'bet_l': 0.25},
    ('OOP', 'low_dry', 'strong'):   {'check': 0.15, 'bet_m': 0.60, 'bet_l': 0.25},
    ('OOP', 'wet', 'strong'):       {'check': 0.20, 'bet_m': 0.50, 'bet_l': 0.30},
    ('OOP', 'monotone', 'strong'):  {'check': 0.35, 'bet_s': 0.30, 'bet_m': 0.35},
    ('OOP', 'paired', 'strong'):    {'check': 0.25, 'bet_m': 0.50, 'bet_l': 0.25},

    # GOOD — thinner value, more checking to control pot
    ('OOP', 'high_dry', 'good'):  {'check': 0.35, 'bet_s': 0.25, 'bet_m': 0.40},
    ('OOP', 'low_dry', 'good'):   {'check': 0.30, 'bet_s': 0.30, 'bet_m': 0.40},
    ('OOP', 'wet', 'good'):       {'check': 0.45, 'bet_s': 0.25, 'bet_m': 0.30},
    ('OOP', 'monotone', 'good'):  {'check': 0.55, 'bet_s': 0.25, 'bet_m': 0.20},
    ('OOP', 'paired', 'good'):    {'check': 0.35, 'bet_s': 0.25, 'bet_m': 0.40},

    # MEDIUM — mostly check, occasional small bet
    ('OOP', 'high_dry', 'medium'):  {'check': 0.60, 'bet_s': 0.25, 'bet_m': 0.15},
    ('OOP', 'low_dry', 'medium'):   {'check': 0.55, 'bet_s': 0.30, 'bet_m': 0.15},
    ('OOP', 'wet', 'medium'):       {'check': 0.70, 'bet_s': 0.20, 'bet_m': 0.10},
    ('OOP', 'monotone', 'medium'):  {'check': 0.75, 'bet_s': 0.15, 'bet_m': 0.10},
    ('OOP', 'paired', 'medium'):    {'check': 0.60, 'bet_s': 0.25, 'bet_m': 0.15},

    # DRAW — semi-bluff, size up on wet boards
    ('OOP', 'high_dry', 'draw'):   {'check': 0.40, 'bet_s': 0.35, 'bet_m': 0.25},
    ('OOP', 'low_dry', 'draw'):    {'check': 0.35, 'bet_s': 0.35, 'bet_m': 0.30},
    ('OOP', 'wet', 'draw'):        {'check': 0.30, 'bet_m': 0.40, 'bet_l': 0.30},
    ('OOP', 'monotone', 'draw'):   {'check': 0.45, 'bet_s': 0.25, 'bet_m': 0.30},
    ('OOP', 'paired', 'draw'):     {'check': 0.35, 'bet_s': 0.30, 'bet_m': 0.35},

    # WEAK_MADE — check, occasionally thin bet on dry
    ('OOP', 'high_dry', 'weak_made'):  {'check': 0.80, 'bet_s': 0.20},
    ('OOP', 'low_dry', 'weak_made'):   {'check': 0.75, 'bet_s': 0.25},
    ('OOP', 'wet', 'weak_made'):       {'check': 0.90, 'bet_s': 0.10},
    ('OOP', 'monotone', 'weak_made'):  {'check': 0.90, 'bet_s': 0.10},
    ('OOP', 'paired', 'weak_made'):    {'check': 0.80, 'bet_s': 0.20},

    # WEAK_DRAW — mostly check, small stab sometimes
    ('OOP', 'high_dry', 'weak_draw'):  {'check': 0.75, 'bet_s': 0.25},
    ('OOP', 'low_dry', 'weak_draw'):   {'check': 0.70, 'bet_s': 0.30},
    ('OOP', 'wet', 'weak_draw'):       {'check': 0.80, 'bet_s': 0.20},
    ('OOP', 'monotone', 'weak_draw'):  {'check': 0.85, 'bet_s': 0.15},
    ('OOP', 'paired', 'weak_draw'):    {'check': 0.75, 'bet_s': 0.25},

    # AIR — check or polarized bluff
    ('OOP', 'high_dry', 'air'):   {'check': 0.65, 'bet_s': 0.10, 'bet_l': 0.25},
    ('OOP', 'low_dry', 'air'):    {'check': 0.60, 'bet_s': 0.10, 'bet_l': 0.30},
    ('OOP', 'wet', 'air'):        {'check': 0.75, 'bet_l': 0.25},
    ('OOP', 'monotone', 'air'):   {'check': 0.80, 'bet_l': 0.20},
    ('OOP', 'paired', 'air'):     {'check': 0.70, 'bet_l': 0.30},
}

# --- IP acting after OOP checks ---
IP_VS_CHECK = {
    # PREMIUM — value bet big, some trapping
    ('IP', 'high_dry', 'premium'):  {'check': 0.30, 'bet_m': 0.25, 'bet_l': 0.45},
    ('IP', 'low_dry', 'premium'):   {'check': 0.25, 'bet_m': 0.25, 'bet_l': 0.50},
    ('IP', 'wet', 'premium'):       {'check': 0.10, 'bet_m': 0.20, 'bet_l': 0.70},
    ('IP', 'monotone', 'premium'):  {'check': 0.10, 'bet_m': 0.25, 'bet_l': 0.65},
    ('IP', 'paired', 'premium'):    {'check': 0.25, 'bet_m': 0.30, 'bet_l': 0.45},

    # NUT
    ('IP', 'high_dry', 'nut'):    {'check': 0.20, 'bet_m': 0.35, 'bet_l': 0.45},
    ('IP', 'low_dry', 'nut'):     {'check': 0.15, 'bet_m': 0.35, 'bet_l': 0.50},
    ('IP', 'wet', 'nut'):         {'check': 0.10, 'bet_m': 0.25, 'bet_l': 0.65},
    ('IP', 'monotone', 'nut'):    {'check': 0.10, 'bet_m': 0.30, 'bet_l': 0.60},
    ('IP', 'paired', 'nut'):      {'check': 0.15, 'bet_m': 0.40, 'bet_l': 0.45},

    # STRONG
    ('IP', 'high_dry', 'strong'):  {'check': 0.15, 'bet_m': 0.60, 'bet_l': 0.25},
    ('IP', 'low_dry', 'strong'):   {'check': 0.10, 'bet_m': 0.65, 'bet_l': 0.25},
    ('IP', 'wet', 'strong'):       {'check': 0.15, 'bet_m': 0.50, 'bet_l': 0.35},
    ('IP', 'monotone', 'strong'):  {'check': 0.25, 'bet_s': 0.30, 'bet_m': 0.45},
    ('IP', 'paired', 'strong'):    {'check': 0.15, 'bet_m': 0.55, 'bet_l': 0.30},

    # GOOD
    ('IP', 'high_dry', 'good'):   {'check': 0.25, 'bet_s': 0.35, 'bet_m': 0.40},
    ('IP', 'low_dry', 'good'):    {'check': 0.20, 'bet_s': 0.35, 'bet_m': 0.45},
    ('IP', 'wet', 'good'):        {'check': 0.35, 'bet_s': 0.30, 'bet_m': 0.35},
    ('IP', 'monotone', 'good'):   {'check': 0.40, 'bet_s': 0.35, 'bet_m': 0.25},
    ('IP', 'paired', 'good'):     {'check': 0.25, 'bet_s': 0.30, 'bet_m': 0.45},

    # MEDIUM
    ('IP', 'high_dry', 'medium'):  {'check': 0.40, 'bet_s': 0.40, 'bet_m': 0.20},
    ('IP', 'low_dry', 'medium'):   {'check': 0.35, 'bet_s': 0.45, 'bet_m': 0.20},
    ('IP', 'wet', 'medium'):       {'check': 0.55, 'bet_s': 0.30, 'bet_m': 0.15},
    ('IP', 'monotone', 'medium'):  {'check': 0.60, 'bet_s': 0.25, 'bet_m': 0.15},
    ('IP', 'paired', 'medium'):    {'check': 0.40, 'bet_s': 0.40, 'bet_m': 0.20},

    # DRAW — semi-bluff IP, can bet bigger
    ('IP', 'high_dry', 'draw'):   {'check': 0.25, 'bet_s': 0.35, 'bet_m': 0.40},
    ('IP', 'low_dry', 'draw'):    {'check': 0.20, 'bet_s': 0.35, 'bet_m': 0.45},
    ('IP', 'wet', 'draw'):        {'check': 0.15, 'bet_m': 0.40, 'bet_l': 0.45},
    ('IP', 'monotone', 'draw'):   {'check': 0.30, 'bet_s': 0.30, 'bet_m': 0.40},
    ('IP', 'paired', 'draw'):     {'check': 0.25, 'bet_s': 0.35, 'bet_m': 0.40},

    # WEAK_MADE — check back for showdown value
    ('IP', 'high_dry', 'weak_made'):  {'check': 0.65, 'bet_s': 0.35},
    ('IP', 'low_dry', 'weak_made'):   {'check': 0.60, 'bet_s': 0.40},
    ('IP', 'wet', 'weak_made'):       {'check': 0.80, 'bet_s': 0.20},
    ('IP', 'monotone', 'weak_made'):  {'check': 0.85, 'bet_s': 0.15},
    ('IP', 'paired', 'weak_made'):    {'check': 0.65, 'bet_s': 0.35},

    # WEAK_DRAW
    ('IP', 'high_dry', 'weak_draw'):  {'check': 0.55, 'bet_s': 0.45},
    ('IP', 'low_dry', 'weak_draw'):   {'check': 0.50, 'bet_s': 0.50},
    ('IP', 'wet', 'weak_draw'):       {'check': 0.65, 'bet_s': 0.35},
    ('IP', 'monotone', 'weak_draw'):  {'check': 0.70, 'bet_s': 0.30},
    ('IP', 'paired', 'weak_draw'):    {'check': 0.55, 'bet_s': 0.45},

    # AIR — polarized bluffs
    ('IP', 'high_dry', 'air'):    {'check': 0.45, 'bet_s': 0.15, 'bet_l': 0.40},
    ('IP', 'low_dry', 'air'):     {'check': 0.40, 'bet_s': 0.15, 'bet_l': 0.45},
    ('IP', 'wet', 'air'):         {'check': 0.55, 'bet_l': 0.45},
    ('IP', 'monotone', 'air'):    {'check': 0.60, 'bet_l': 0.40},
    ('IP', 'paired', 'air'):      {'check': 0.50, 'bet_l': 0.50},
}

# --- Facing a bet: {(texture, bucket): {action: prob}} ---
FACING_BET = {
    # PREMIUM — raise for max value
    ('high_dry', 'premium'):  {'call': 0.35, 'raise': 0.65},
    ('low_dry', 'premium'):   {'call': 0.30, 'raise': 0.70},
    ('wet', 'premium'):       {'call': 0.25, 'raise': 0.75},
    ('monotone', 'premium'):  {'call': 0.30, 'raise': 0.70},
    ('paired', 'premium'):    {'call': 0.30, 'raise': 0.70},

    # NUT — mostly raise, some slowplay calls
    ('high_dry', 'nut'):   {'call': 0.40, 'raise': 0.60},
    ('low_dry', 'nut'):    {'call': 0.35, 'raise': 0.65},
    ('wet', 'nut'):        {'call': 0.35, 'raise': 0.65},
    ('monotone', 'nut'):   {'call': 0.45, 'raise': 0.55},
    ('paired', 'nut'):     {'call': 0.40, 'raise': 0.60},

    # STRONG — mostly call, occasional raise
    ('high_dry', 'strong'):  {'call': 0.80, 'raise': 0.20},
    ('low_dry', 'strong'):   {'call': 0.75, 'raise': 0.25},
    ('wet', 'strong'):       {'call': 0.75, 'raise': 0.25},
    ('monotone', 'strong'):  {'call': 0.85, 'raise': 0.15},
    ('paired', 'strong'):    {'call': 0.80, 'raise': 0.20},

    # GOOD — call most, fold some on scary boards
    ('high_dry', 'good'):   {'call': 0.80, 'fold': 0.10, 'raise': 0.10},
    ('low_dry', 'good'):    {'call': 0.75, 'fold': 0.10, 'raise': 0.15},
    ('wet', 'good'):        {'call': 0.65, 'fold': 0.25, 'raise': 0.10},
    ('monotone', 'good'):   {'call': 0.60, 'fold': 0.30, 'raise': 0.10},
    ('paired', 'good'):     {'call': 0.75, 'fold': 0.15, 'raise': 0.10},

    # MEDIUM — call or fold depending on texture
    ('high_dry', 'medium'):  {'call': 0.65, 'fold': 0.35},
    ('low_dry', 'medium'):   {'call': 0.60, 'fold': 0.40},
    ('wet', 'medium'):       {'call': 0.45, 'fold': 0.55},
    ('monotone', 'medium'):  {'call': 0.40, 'fold': 0.60},
    ('paired', 'medium'):    {'call': 0.55, 'fold': 0.45},

    # DRAW — call for odds, sometimes raise as semi-bluff
    ('high_dry', 'draw'):   {'call': 0.55, 'raise': 0.20, 'fold': 0.25},
    ('low_dry', 'draw'):    {'call': 0.50, 'raise': 0.25, 'fold': 0.25},
    ('wet', 'draw'):        {'call': 0.45, 'raise': 0.30, 'fold': 0.25},
    ('monotone', 'draw'):   {'call': 0.50, 'raise': 0.20, 'fold': 0.30},
    ('paired', 'draw'):     {'call': 0.50, 'raise': 0.25, 'fold': 0.25},

    # WEAK_MADE — fold most, call small bets
    ('high_dry', 'weak_made'):  {'fold': 0.55, 'call': 0.45},
    ('low_dry', 'weak_made'):   {'fold': 0.45, 'call': 0.55},
    ('wet', 'weak_made'):       {'fold': 0.65, 'call': 0.35},
    ('monotone', 'weak_made'):  {'fold': 0.70, 'call': 0.30},
    ('paired', 'weak_made'):    {'fold': 0.55, 'call': 0.45},

    # WEAK_DRAW — fold or call for cheap draw
    ('high_dry', 'weak_draw'):  {'fold': 0.55, 'call': 0.45},
    ('low_dry', 'weak_draw'):   {'fold': 0.55, 'call': 0.45},
    ('wet', 'weak_draw'):       {'fold': 0.60, 'call': 0.40},
    ('monotone', 'weak_draw'):  {'fold': 0.65, 'call': 0.35},
    ('paired', 'weak_draw'):    {'fold': 0.55, 'call': 0.45},

    # AIR — mostly fold, occasional bluff raise
    ('high_dry', 'air'):   {'fold': 0.70, 'raise': 0.15, 'call': 0.15},
    ('low_dry', 'air'):    {'fold': 0.65, 'raise': 0.20, 'call': 0.15},
    ('wet', 'air'):        {'fold': 0.75, 'raise': 0.15, 'call': 0.10},
    ('monotone', 'air'):   {'fold': 0.80, 'raise': 0.10, 'call': 0.10},
    ('paired', 'air'):     {'fold': 0.70, 'raise': 0.15, 'call': 0.15},
}


def get_strategy(position, texture, bucket, facing_bet=False):
    """Look up strategy for a given context."""
    if facing_bet:
        return FACING_BET.get((texture, bucket), {'fold': 0.5, 'call': 0.5})
    if position == 'OOP':
        return OOP_STRATEGY.get(('OOP', texture, bucket), {'check': 1.0})
    return IP_VS_CHECK.get(('IP', texture, bucket), {'check': 1.0})


def get_correct_actions(strategy):
    """Determine acceptable actions from a mixed strategy."""
    sorted_actions = sorted(strategy.items(), key=lambda x: -x[1])
    best_action, best_prob = sorted_actions[0]

    if best_prob >= 0.50:
        return [best_action]

    # Mixed — accept top two if both substantial
    correct = [best_action]
    if len(sorted_actions) > 1:
        second_action, second_prob = sorted_actions[1]
        if second_prob >= 0.25:
            correct.append(second_action)
    return correct


# ================================================================
# Load pre-computed strategies from JSON if available
# ================================================================

_DATA_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'strategies.json')

if os.path.exists(_DATA_PATH):
    with open(_DATA_PATH) as _f:
        _SOLVED = json.load(_f)

    _strats = _SOLVED.get('strategies', {})

    # Override OOP_STRATEGY
    for tex in TEXTURES:
        for bkt_strat in (_strats.get('OOP', {}).get(tex, {})).items():
            bkt, strat = bkt_strat
            if strat:
                OOP_STRATEGY[('OOP', tex, bkt)] = strat

    # Override IP_VS_CHECK
    for tex in TEXTURES:
        for bkt_strat in (_strats.get('IP', {}).get(tex, {})).items():
            bkt, strat = bkt_strat
            if strat:
                IP_VS_CHECK[('IP', tex, bkt)] = strat

    # Override FACING_BET
    for tex in TEXTURES:
        for bkt_strat in (_strats.get('FACING_BET', {}).get(tex, {})).items():
            bkt, strat = bkt_strat
            if strat:
                FACING_BET[(tex, bkt)] = strat
