// Orders the 169 starting hands by equity vs a random hand (Monte Carlo, seeded).
// Output: src/engine/hu/preflopRank.js. Run once: node scripts/preflop-rank.mjs
import { writeFileSync } from 'node:fs';
import { evaluate, rank, suit } from '../src/engine/hu/hand.js';
import { rng } from '../src/engine/hu/game.js';

const R = '23456789TJQKA';
const rand = rng(2026);
const hands = [];
for (let a = 12; a >= 0; a--) for (let b = a; b >= 0; b--) {
  if (a === b) hands.push({ key: R[a] + R[b], cards: [4 * a, 4 * b + 1] });
  else {
    hands.push({ key: R[a] + R[b] + 's', cards: [4 * a, 4 * b] });
    hands.push({ key: R[a] + R[b] + 'o', cards: [4 * a, 4 * b + 1] });
  }
}
const N = 6000;
for (const h of hands) {
  let win = 0;
  for (let i = 0; i < N; i++) {
    const deck = [];
    for (let c = 0; c < 52; c++) if (c !== h.cards[0] && c !== h.cards[1]) deck.push(c);
    for (let k = 0; k < 7; k++) { const j = k + Math.floor(rand() * (deck.length - k)); [deck[k], deck[j]] = [deck[j], deck[k]]; }
    const opp = [deck[0], deck[1]], b = deck.slice(2, 7);
    const v1 = evaluate([...h.cards, ...b]), v2 = evaluate([...opp, ...b]);
    win += v1 > v2 ? 1 : v1 === v2 ? 0.5 : 0;
  }
  h.eq = win / N;
}
hands.sort((x, y) => y.eq - x.eq);
const combos = (k) => (k.length === 2 ? 6 : k.endsWith('s') ? 4 : 12);
let cum = 0;
const rows = hands.map(h => { cum += combos(h.key); return [h.key, +h.eq.toFixed(3), +(cum / 1326).toFixed(4)]; });
writeFileSync('src/engine/hu/preflopRank.js',
  `// Generated by scripts/preflop-rank.mjs: the 169 starting hands ordered by equity vs a random hand.\n` +
  `// [hand, equity vs random, cumulative share of all 1326 combos at or above this hand]\n` +
  `export const PREFLOP_RANK = ${JSON.stringify(rows)};\n`);
console.log(rows.slice(0, 8), rows.slice(-3));
